language: python
python:
  - "3.11"

install:
  - cd backend
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - pytest -v --tb=short

notifications:
  email:
    on_success: always
    on_failure: always

cache:
  directories:
    - $HOME/.cache/pip